[package]
name = "osu-irc-3"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
regex = "1.10.3"
linkify = "0.10.0"
serenity = "0.12.1"
async-trait = "0.1.77"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }